### ISSUE TITLE
Hello sir, I'm getting an error while making this app, i.e., Unhandled Runtime Error Error: Text content does not match server-rendered HTML.  See more info here: https://nextjs.org/docs/messages/react-hydration-error. After i created the CreatorCard amd NFTCard components and imported in indej.js file of pages folder. Please help me sir.

### ISSUE THREAD

**Issue by vashu10** [CoderGhost37/NFT-Marketplace-CryptoKet#2]

**Comment by CoderGhost37** [comment]
It may be happening because of the latest version of IPFS. In the new version there were some major changes due to which the app is breaking. Do check it out. 
Link: https://ipfs.tech/
Hope this helps.

**Comment by vashu10** [comment]
Sir, I haven't reached there yet. I'm currently working on the front-end part.

**Comment by CoderGhost37** [comment]
Send your code snippets.
